#pragma once
#include <Windows.h>

constexpr static int EVENT_COUNTS = 8;

struct Events {

	HANDLE IDLE_FILE_INPUT = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE IDLE_RECEIVE_ENQ = CreateEvent(NULL, FALSE, FALSE, NULL);

	// To set state to RTS
	HANDLE PREP_TX = CreateEvent(NULL, FALSE, FALSE, NULL);

	HANDLE TX_RECEIVE_ACK = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE TX_RECEIVE_REQ = CreateEvent(NULL, FALSE, FALSE, NULL);

	HANDLE RTR_FILE_INPUT = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE RTR_RECEIVE_FRAME = CreateEvent(NULL, FALSE, FALSE, NULL);
	HANDLE RTR_RECEIVE_EOT = CreateEvent(NULL, FALSE, FALSE, NULL);


	HANDLE handles[EVENT_COUNTS] = {
		IDLE_FILE_INPUT,	//0
		IDLE_RECEIVE_ENQ,	//1
		PREP_TX,			//2
		TX_RECEIVE_ACK,		//3
		TX_RECEIVE_REQ,		//4
		RTR_FILE_INPUT,		//5
		RTR_RECEIVE_FRAME,	//6
		RTR_RECEIVE_EOT,	//7
	};

};